pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('differnce between two commits') {
            steps {
                sh 'git diff --name-only $GIT_PREVIOUS_COMMIT'
            }
        }
        stage('Build only on incremental changes'){
            when { changeset "*/componentA/**"} //Will execute your steps if any file change inside the componentA directory
                steps {
                    echo 'Build from changed files'
                }
        }
    }
}
