pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('differnce between two commits') {
            steps {
                sh 'git diff --name-only $GIT_PREVIOUS_COMMIT'
            }
        }
        stage('Build only on incremental changes'){
            when { changeset "*/componentA/**"} //Will execute your steps if any file change inside the componentA directory
                steps {
                    echo 'Build from changed files'
                }
        }
        
        stage('Build only on incremental changes from last 2 git commits'){
                steps {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'AWS_Credentials', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                        sh 'git diff --name-only --diff-filter=AMR HEAD^^ HEAD > modified_files.txt'
                        sh 'for files in `cat modified_files.txt`; do /usr/local/bin/aws s3 cp $files s3://tf-bucket-04jan/test/ ; done'
                           
                        
                    }
                }
        }
    }
}

// testing
